# Generated by Django 4.0.4 on 2022-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=1000)),
                ('popularity', models.CharField(max_length=1000)),
                ('interpret', models.CharField(max_length=1000)),
            ],
        ),
    ]
